[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1D4ED8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"
